services:
  ollama:
    # Use your custom Dockerfile to build the Ollama service
    build: ./ollama
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      # Keep the health check, but give it more time to start up and pull the model
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    deploy: # for laptop nvidia GPU support
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  streamlit:
    build: .
    container_name: document_verifier
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      # --- IMPORTANT CHANGE HERE ---
      # Changed OLLAMA_URL to OLLAMA_HOST for proper client configuration
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    command: streamlit run app.py --server.address=0.0.0.0