
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: >
      sh -c "ollama serve & 
             sleep 10 && 
             ollama pull gemma:2b && 
             wait"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5

  streamlit:
    build: .
    container_name: document_verifier
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy
    command: streamlit run app.py --server.address=0.0.0.0