services:
  ollama:
    # Use your custom Dockerfile to build the Ollama service
    build: ./ollama
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      # Keep the health check, but give it more time to start up and pull the model
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 15s # Increased timeout slightly
      retries: 5
      start_period: 120s # Significantly increased start_period for first-time model pull

  streamlit:
    build: .
    container_name: document_verifier
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy # Now ollama should become healthy after pulling the model
    command: streamlit run app.py --server.address=0.0.0.0